<!-- 
    The home page displaying the main page for the web application, when
    users open the website, the nav bar is generated by the nav.php page which
    runs throughout all of our pages, keeping the design similar. 
    
 -->
<?php include("header.php");?>
<link ref style.css>
<!DOCTYPE html>
<html>
<title>HomePage</title>

    <body>

        <div class ="mainContent" id ="mainCon">

            <h2>
                Why Choose Us?
            </h2>   
            <div class ="para-1">
            <p>
                We offer the best muscular physiotherapy services within the Waikato Region.
                If you're suffering from an injury, we can help rehabilitate you and get you back
                up to speed.
            </p>
            <p>
                Whether its from a sports injury, a fall, or just from repetitive strain,
                we will strive to help you feel your best.
            </p>
            </div>

            <!-- Royalty free physio pics from https://www.dreamstime.com/photos-images/physiotherapy.html -->
            <div class="pic-container">
                <div class="pics">
                    <img src="Assets/pic1.jpg" alt="physio-pic"  height="150" width="250">                                              
                    <img src="Assets/pic3.jpg" alt="physio-pic"  height="150" width="300">                                       
                    <img src="Assets/pic2.jpg" alt="physio-pic"  height="150" width="250">                                    
                 </div>

             </div>    
            <h2>
                What we offer...
            </h2>

            <div class="para-2">
                
                    <div class="row">
                    <div class="col">
                    <h3>Short Massage</h3>
                    <p style="text-align: justify;">
                        For when its just a small amount of work needed
                        on your muscles, light work done to get you through the 
                        day. Popular among professional athletes
                        looking to get the best recovery. </p><p style="text-align: center;"><b>$40</b>
                    </p>
                    </div>
                    <div class="col">            
                    <h3>Medium Massage</h3>
                    <p style="text-align: justify">
                        The middle ground massage, if there's a moderate amount
                        of work that needs done on a larger muscle group for
                        your body (such as a sprain or minor injury), this is the choice for you. </p><p style="text-align: center;"> <b>$60</b>
                    </p>
                    </div>
                    <div class="col">
                    <h3>Long Massage</h3>
                    <p style="text-align: justify;">
                        This massage is for heavy rehabilitation, if you need to 
                        have some major therapy done or need help to function 
                        properly, we recommend this one. It will change your 
                        life. </p><p style="text-align: center;"> <b>$80</b>
                    </div>
                    </div>
                
            </div>
        </div>
        
    </body>

</html>


